### ISSUE TITLE
Fix some accessibility issues

### ISSUE THREAD

**Issue by federa7675** [vinceliuice/ChromeOS-kde#14]
1. There are some accessibility issue with combo-boxes and general text input fields in this theme that make it hard for me to recognize them in various contexts. Here are some detailed explanation with screenshots:

Current design | Desired look | Upstream
------------ | ------------- | -------------
![image](https://user-images.githubusercontent.com/64138927/80822313-1c7ccf00-8be3-11ea-86ee-a29ba1312a9b.png) | ![image](https://user-images.githubusercontent.com/64138927/80822254-fa834c80-8be2-11ea-9da2-d4ca8dedbb98.png) | ![image](https://user-images.githubusercontent.com/64138927/80822107-ad06df80-8be2-11ea-82b4-71321435bb61.png)

2. When having multiple tabs open e.g. (in kate text editor) the buttons used to navigate the tabs is bigger that it should (broken)

Current design | Desired look
------------ | -------------
![image](https://user-images.githubusercontent.com/64138927/80822393-4cc46d80-8be3-11ea-8537-88fc54612760.png) | ![image](https://user-images.githubusercontent.com/64138927/80822440-6665b500-8be3-11ea-8cb8-24e02b0519ac.png)

* the desktop theme already has some combo-boxes and text input field that are very good I suggest you use those in the Kvantum theme.

Combo-box | Text input field
------------ | -------------
![image](https://user-images.githubusercontent.com/64138927/80823181-d7599c80-8be4-11ea-8de2-0a647bf6c338.png) | ![image](https://user-images.githubusercontent.com/64138927/80824028-51d6ec00-8be6-11ea-9948-a6cb0f310ca6.png)

**Comment by federa7675** [comment]
@vinceliuice

**Comment by vinceliuice** [comment]
No problem! I'll update this

**Comment by federa7675** [comment]
Thanks :)

**Comment by digitalethics** [comment]
@federa7675 Why did you close the issue? I think this is not implemented yet.

**Comment by federa7675** [comment]
Thanks @vinceliuice it looks amazing and usable now 😊️

![image](https://user-images.githubusercontent.com/64138927/81943653-52b74700-9604-11ea-923c-920cb944374a.png)

![image](https://user-images.githubusercontent.com/64138927/81943962-bccfec00-9604-11ea-98f5-7bfc49cb5413.png)

**Comment by vinceliuice** [comment]
You are welcome! @federa7675
