### ISSUE TITLE
Add a Dark theme

### ISSUE THREAD

**Issue by oskarsh** [vinceliuice/ChromeOS-kde#2]
If using the ChromeOS-dark colors in Kde it will still leave a white outline defined by the theme. 

Could you please add a dark theme?

**Comment by vinceliuice** [comment]
You can download the last update, I already uploaded a dark theme

**Comment by oskarsh** [comment]
I just cloned the repo and set ChromeOS-dark inside my Kvantum theme, while I get a basic dark-theme one thing that still persists is the tiny border at the lower end of the window see screenshot

![grafik](https://user-images.githubusercontent.com/36965591/73846429-d0f59780-4824-11ea-88d9-761191d0034a.png)


You can see in the screenshot that the white border persists at the lower end of the window (resize area). It even shows inside the Window decoration screen.

**Comment by vinceliuice** [comment]
You can set the ChromeOS-dark aurorae theme, this one is made for the light version,

**Comment by oskarsh** [comment]
I cloned the repo and used the ./install.sh I now got the option to select ChromeOS-dark. 

btw. great work on all your themes!

Thanks
