### ISSUE TITLE
Disable blur in dark theme?

### ISSUE THREAD

**Issue by codic12** [vinceliuice/ChromeOS-kde#22]
Hi @vinceliuice i really appreciate your great work, do you know what parts of the rc file to edit to change background color and disable blur? thanks so much

**Comment by codic12** [comment]
(I'm talking about the window decorations)

**Comment by codic12** [comment]
Figured it out, just edit the chromeOS Blue theme

**Comment by nigelwarning** [comment]
How did you do this exactly? Would love to do it tho.

**Comment by codic12** [comment]
I don't use KDE anymore, switched to XFCE, but I took the "Blue" version with the blue window decorations and edited the svg with inkscape.
