### ISSUE TITLE
Kubuntu 18.04 - Type Clock unavailable

### ISSUE THREAD

**Issue by hsehdar** [vinceliuice/ChromeOS-kde#3]
Getting error on the sddm 

> type clock unavailable
> QtQuick.Controls version 2.5 is not available

Any tips?

**Comment by vinceliuice** [comment]
I fixed this, you can download the last update

**Comment by hsehdar** [comment]
> I fixed this, you can download the last update

Thanks, shall check it.

**Comment by hsehdar** [comment]
Yes, the latest source should overwrite the default available in KDE.
Issue shall be closed. Will wait and see in Ubuntu 20.04.
