### ISSUE TITLE
Theme does not install correctly from KDE software

### ISSUE THREAD

**Issue by stpr-dev** [vinceliuice/ChromeOS-kde#4]
Installing the theme from KDE's apps results in the theme not installing properly. By this I mean that the theme is not selectable in the 'Global Theme' section. On the other hand, installing it directly from source works fine (i.e. download from GitHub and running install.sh). The size on the store also shows as 0B (see attached screenshot), which is a bit odd to me.
![Screenshot_20200305_225920](https://user-images.githubusercontent.com/15972594/76046003-18ab3400-5f35-11ea-935e-b1c0772288b1.png)

**Comment by vinceliuice** [comment]
Delete it and try again, maybe it's just a net issue

**Comment by stpr-dev** [comment]
Tried doing it several times over several days and also restarted my computer, none of it appears to help.

**Comment by stpr-dev** [comment]
Ok so I tried installing the theme again from Discover, it installs everything except the kvantum theme.

**Comment by vinceliuice** [comment]
I fixed this issue!

**Comment by digitalethics** [comment]
@vinceliuice While it installs via the Plasma _Global Theme_ settings, switching between light, dark, and colour editions is not very straightforward. I've raised a new issue #8 to address this.
