### ISSUE TITLE
Switch component is rendered badly

### ISSUE THREAD

**Issue by Grief** [vinceliuice/ChromeOS-kde#42]
Outer part's shape doesn't follow the shape of the inner part, badly rounded and has a horizonal line in the middle which looks like a bug:
![image](https://github.com/user-attachments/assets/a13864e7-fedb-49a2-9a1f-ed411196ed65)
![image](https://github.com/user-attachments/assets/8d7bfa44-0899-4c8c-80f2-bca11492fdab)

**Comment by vinceliuice** [comment]
Restart your desktop

**Comment by Grief** [comment]
I feel stupid now... Thank you Vince!
![image](https://github.com/user-attachments/assets/ceef726f-bd53-46ca-a12a-5f57139378e7)

**Comment by Grief** [comment]
The right side of the circle is still cut a little bit though

**Comment by vinceliuice** [comment]
Now it's ok

**Comment by Grief** [comment]
Thank you! Looks better now
![image](https://github.com/user-attachments/assets/cb7e70cb-8868-4c38-af08-9b1455e63961)
