### ISSUE TITLE
Square window decorations?

### ISSUE THREAD

**Issue by francoism90** [vinceliuice/ChromeOS-kde#5]
Would it be possible to add square window decorations instead of the rounded one? Or is it easy to modified them?

Could you also please share the wallpaper?

Thanks for your great work!

**Comment by digitalethics** [comment]
> square window decorations instead of the rounded one

I think part of the appeal of a ChromeOS-styled theme is its roundness. Do you mean the round shadows upon hovering over the titlebar buttons _Minimize_, _Maximize_, and _Close_?

**Comment by francoism90** [comment]
@digitalethics No, I do mean the window decoration itself.
